"emojis":
- "name": "77"
  "src": "https://raw.githubusercontent.com/jordanbuchman/steamoji/master/games/Silver Bullet: Prometheus/images/77.png"
- "name": "KickAss"
  "src": "https://raw.githubusercontent.com/jordanbuchman/steamoji/master/games/Silver Bullet: Prometheus/images/KickAss.png"
- "name": "BlamBlam"
  "src": "https://raw.githubusercontent.com/jordanbuchman/steamoji/master/games/Silver Bullet: Prometheus/images/BlamBlam.png"
- "name": "HelpCall"
  "src": "https://raw.githubusercontent.com/jordanbuchman/steamoji/master/games/Silver Bullet: Prometheus/images/HelpCall.png"
"title": "Silver Bullet: Prometheus"
